#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.135                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS =  -Wall -Wno-multichar -DLINUX
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g -DDEBUG
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB) -lpthread -lrt -lcurl
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/id4-pi

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB) -lpthread -lrt -lcurl
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/id4-pi

OBJ_DEBUG = $(OBJDIR_DEBUG)/wsfdata.o $(OBJDIR_DEBUG)/wsfcode.o $(OBJDIR_DEBUG)/webmain.o $(OBJDIR_DEBUG)/webio/webutils.o $(OBJDIR_DEBUG)/webio/websys.o $(OBJDIR_DEBUG)/webio/webobjs.o $(OBJDIR_DEBUG)/webio/webio.o $(OBJDIR_DEBUG)/ID4Clock.o $(OBJDIR_DEBUG)/webio/webfs.o $(OBJDIR_DEBUG)/webio/webclib.o $(OBJDIR_DEBUG)/serport.o $(OBJDIR_DEBUG)/id4-pi.o $(OBJDIR_DEBUG)/ftpupload.o $(OBJDIR_DEBUG)/ID4Serial.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/wsfdata.o $(OBJDIR_RELEASE)/wsfcode.o $(OBJDIR_RELEASE)/webmain.o $(OBJDIR_RELEASE)/webio/webutils.o $(OBJDIR_RELEASE)/webio/websys.o $(OBJDIR_RELEASE)/webio/webobjs.o $(OBJDIR_RELEASE)/webio/webio.o $(OBJDIR_RELEASE)/ID4Clock.o $(OBJDIR_RELEASE)/webio/webfs.o $(OBJDIR_RELEASE)/webio/webclib.o $(OBJDIR_RELEASE)/serport.o $(OBJDIR_RELEASE)/id4-pi.o $(OBJDIR_RELEASE)/ftpupload.o $(OBJDIR_RELEASE)/ID4Serial.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/webio || mkdir -p $(OBJDIR_DEBUG)/webio

after_debug: 

debug: before_debug out_debug after_debug

out_debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(OBJ_DEBUG) $(LIB_DEBUG) -o $(OUT_DEBUG)

$(OBJDIR_DEBUG)/wsfdata.o: wsfdata.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wsfdata.c -o $(OBJDIR_DEBUG)/wsfdata.o

$(OBJDIR_DEBUG)/wsfcode.o: wsfcode.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c wsfcode.c -o $(OBJDIR_DEBUG)/wsfcode.o

$(OBJDIR_DEBUG)/webmain.o: webmain.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webmain.c -o $(OBJDIR_DEBUG)/webmain.o

$(OBJDIR_DEBUG)/webio/webutils.o: webio/webutils.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webio/webutils.c -o $(OBJDIR_DEBUG)/webio/webutils.o

$(OBJDIR_DEBUG)/webio/websys.o: webio/websys.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webio/websys.c -o $(OBJDIR_DEBUG)/webio/websys.o

$(OBJDIR_DEBUG)/webio/webobjs.o: webio/webobjs.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webio/webobjs.c -o $(OBJDIR_DEBUG)/webio/webobjs.o

$(OBJDIR_DEBUG)/webio/webio.o: webio/webio.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webio/webio.c -o $(OBJDIR_DEBUG)/webio/webio.o

$(OBJDIR_DEBUG)/ID4Clock.o: ID4Clock.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ID4Clock.c -o $(OBJDIR_DEBUG)/ID4Clock.o

$(OBJDIR_DEBUG)/webio/webfs.o: webio/webfs.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webio/webfs.c -o $(OBJDIR_DEBUG)/webio/webfs.o

$(OBJDIR_DEBUG)/webio/webclib.o: webio/webclib.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c webio/webclib.c -o $(OBJDIR_DEBUG)/webio/webclib.o

$(OBJDIR_DEBUG)/serport.o: serport.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c serport.c -o $(OBJDIR_DEBUG)/serport.o

$(OBJDIR_DEBUG)/id4-pi.o: id4-pi.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c id4-pi.c -o $(OBJDIR_DEBUG)/id4-pi.o

$(OBJDIR_DEBUG)/ftpupload.o: ftpupload.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ftpupload.c -o $(OBJDIR_DEBUG)/ftpupload.o

$(OBJDIR_DEBUG)/ID4Serial.o: ID4Serial.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ID4Serial.c -o $(OBJDIR_DEBUG)/ID4Serial.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/webio

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/webio || mkdir -p $(OBJDIR_RELEASE)/webio

after_release: 

release: before_release out_release after_release

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)/wsfdata.o: wsfdata.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wsfdata.c -o $(OBJDIR_RELEASE)/wsfdata.o

$(OBJDIR_RELEASE)/wsfcode.o: wsfcode.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c wsfcode.c -o $(OBJDIR_RELEASE)/wsfcode.o

$(OBJDIR_RELEASE)/webmain.o: webmain.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webmain.c -o $(OBJDIR_RELEASE)/webmain.o

$(OBJDIR_RELEASE)/webio/webutils.o: webio/webutils.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webio/webutils.c -o $(OBJDIR_RELEASE)/webio/webutils.o

$(OBJDIR_RELEASE)/webio/websys.o: webio/websys.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webio/websys.c -o $(OBJDIR_RELEASE)/webio/websys.o

$(OBJDIR_RELEASE)/webio/webobjs.o: webio/webobjs.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webio/webobjs.c -o $(OBJDIR_RELEASE)/webio/webobjs.o

$(OBJDIR_RELEASE)/webio/webio.o: webio/webio.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webio/webio.c -o $(OBJDIR_RELEASE)/webio/webio.o

$(OBJDIR_RELEASE)/ID4Clock.o: ID4Clock.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ID4Clock.c -o $(OBJDIR_RELEASE)/ID4Clock.o

$(OBJDIR_RELEASE)/webio/webfs.o: webio/webfs.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webio/webfs.c -o $(OBJDIR_RELEASE)/webio/webfs.o

$(OBJDIR_RELEASE)/webio/webclib.o: webio/webclib.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c webio/webclib.c -o $(OBJDIR_RELEASE)/webio/webclib.o

$(OBJDIR_RELEASE)/serport.o: serport.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c serport.c -o $(OBJDIR_RELEASE)/serport.o

$(OBJDIR_RELEASE)/id4-pi.o: id4-pi.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c id4-pi.c -o $(OBJDIR_RELEASE)/id4-pi.o

$(OBJDIR_RELEASE)/ftpupload.o: ftpupload.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ftpupload.c -o $(OBJDIR_RELEASE)/ftpupload.o

$(OBJDIR_RELEASE)/ID4Serial.o: ID4Serial.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ID4Serial.c -o $(OBJDIR_RELEASE)/ID4Serial.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/webio

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

